name: glass_morphic_lite
description: "A high-performance, lightweight glassmorphic container widget for Flutter with zero external dependencies."
version: 0.0.1
homepage: https://github.com/mbonimana/glass_morphic_lite
repository: https://github.com/mbonimana/glass_morphic_lite

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:



